//Bringing in UI elements
const beginBtn = document.getElementById("begin-btn");
const rollBtn = docment.getElementById("roll-btn");
const nextBtn = document.getElementById("next-btn");
const playerHealthElement = document.getElementById("player-health");
const enemyHealthElement = document.getElementById("enemy-health");
const middleContainer = document.getElementById("middle-container");
const turnCounterElement = document.getElementById("turn-counter");
const whoseTurnElement = document.getElementById("whose-turn");
